model_path: "/home/data/panlingzhi/models"
output_path: "outputs"
sd_version: "v5"
model_id: "stable-diffusion-v1-5"
controlnet_id: "sd-controlnet-scribble"
controlnet_scale: 0.8
ipa_id: "ip_adapter"
ip_scale: 0.4

input_image: "data/truck-sample.png"
mask_image: "data/truck-mask.png"
ip_image: "data/starry.png"
cond_image: "data/motor.png"
prompt: "motorbike"
negative_prompt: ""

cfg: 7.5
W: 512
H: 512
num: 1

seed: 91
step: 100
op_interval: 10
num_gradient_ops: 10
gamma: 0.8
lr_warmup: 0.01
lr: 0.025
lr_f: "exp"
coef: 150
coef_f: "linear"
momentum: 0.7
fp16: true




