model_path: "/home/data/panlingzhi/models"
output_path: "outputs"
sd_version: "v5"
model_id: "stable-diffusion-v1-5"
ipa_id: "ip_adapter"
ip_scale: 0.6

input_image: "data/monet-sample.png"
mask_image: "data/monet-mask.png"
ip_image: "data/starry.png"
prompt: "sky"
negative_prompt: ""

cfg: 7.5
W: 512
H: 512
num: 1

seed: 66
step: 100
op_interval: 10
num_gradient_ops: 10
gamma: 0.8
lr_warmup: 0.007
lr: 0.03
lr_f: "exp"
coef: 150
coef_f: "linear"
momentum: 0.7
fp16: true




